export default {
  MAIL_STATUS_READY: "MAIL_STATUS_READY",
  MAIL_STATUS_SEND_SUCCESS: "MAIL_STATUS_SEND_SUCCESS",
  MAIL_STATUS_SEND_FAIL: "MAIL_STATUS_SEND_FAIL",
  MAIL_STATUS_SENDING: "MAIL_STATUS_SENDING"
};

export const MAIL_STATUS_MAP: {[key: string]: string} = {
  MAIL_STATUS_READY: "待发送",
  MAIL_STATUS_SENDING: "发送中",
  MAIL_STATUS_SEND_SUCCESS: "发送成功",
  MAIL_STATUS_SEND_FAIL: "发送失败"
};
