export default {
  MAIL_STATUS_READY: "MAIL_STATUS_READY",
  MAIL_STATUS_SEND_SUCCESS: "MAIL_STATUS_SEND_SUCCESS",
  MAIL_STATUS_SEND_FAIL: "MAIL_STATUS_SEND_FAIL",
};

export const MAIL_STATUS_MAP = {
  MAIL_STATUS_READY: "待发送",
  MAIL_STATUS_SEND_SUCCESS: "发送成功",
  MAIL_STATUS_SEND_FAIL: "发送失败"
};
